# Generated by Django 4.2 on 2023-04-07 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark', models.ImageField(upload_to='media/')),
                ('decoded', models.ImageField(upload_to='media/')),
                ('disparity', models.ImageField(upload_to='media/')),
                ('edited', models.ImageField(upload_to='media/')),
                ('light', models.ImageField(upload_to='media/')),
                ('lookup', models.ImageField(upload_to='media/')),
                ('mask', models.ImageField(upload_to='media/')),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chartjs.iteration')),
            ],
        ),
    ]
