# Generated by Django 4.2 on 2023-04-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='iteration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='chartjs.iteration'),
        ),
    ]
