# Generated by Django 4.2 on 2023-04-07 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0002_alter_data_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chartjs.iteration'),
        ),
    ]
