# Generated by Django 4.2 on 2023-04-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0003_alter_data_iteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='iteration',
        ),
        migrations.AddField(
            model_name='iteration',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chartjs.data'),
        ),
    ]
