# Generated by Django 4.2 on 2023-04-07 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0004_remove_data_iteration_iteration_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteration',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='iteration',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='chartjs.iteration'),
            preserve_default=False,
        ),
    ]
