# Generated by Django 4.2 on 2023-04-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0005_remove_iteration_data_data_iteration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chartjs.data')),
            ],
        ),
    ]
