# Generated by Django 4.2 on 2023-04-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0007_chartdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartData',
        ),
    ]
