# Generated by Django 4.2 on 2023-04-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0008_delete_chartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='mse',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='ssim_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
