# Generated by Django 4.2 on 2023-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0010_alter_data_mse_alter_data_ssim_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='mse',
            field=models.FloatField(default=0.0, max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='ssim_score',
            field=models.FloatField(default=0.0, max_length=3),
        ),
    ]
